apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: registry
spec:
  secretName: harbor-tls-secret
  issuerRef:
    name: ztcr-ca-issuer
    kind: ClusterIssuer
  commonName: registry.ztcr.local
  dnsNames:
    - registry.ztcr.local
