prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 512Mi

grafana:
  enabled: true
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.ztcr.local
  adminPassword: "Grafana12345"

alertmanager:
  enabled: false

prometheusOperator:
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false
